#!/bin/bash

python3 train.py --batch-size=32 --topo --topo-every 1 --kelp-every=1 --n-layers=1 --d-model=2 --n-heads=4 --tokenizer_initial_nr=10000 --lr=0.005 --batches-per-epoch=32 --val-batches=32 --task=turnstile --max-seq-len=128 --epochs 10000
